### ISSUE TITLE
[1/31/23] Y1 Q2 Deliverable - Progress Report

### ISSUE THREAD

**Issue by isalanglois** [urbanopt/URBANopt-ghp-des-modeling-project#1]
-Quarterly progress report sent to DOE by due date. Progress report will discuss the status of the enhancements to the GHE design tool, and the development URBANopt SDK workflows for GHP design and simulation. 

-Will also report on status of Ladybug Tools efforts integrate the URBANopt workflows which are still under development.

**Comment by mitchute** [comment]
Completed

**Comment by mitchute** [comment]
@isalanglois can close this issue? It looks like I don't have the permissions on this repo to close it myself.
